# Generated by Django 4.1.3 on 2022-11-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('bus', 'Day Scholor'), ('hos', 'Hosteller')], default='bus', max_length=3),
        ),
    ]
