# Generated by Django 4.1.3 on 2022-11-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('bus', 'Day Scholor'), ('hos', 'Hosteller'), ('inc', 'Transport department')], default='bus', max_length=3),
        ),
    ]
