# Generated by Django 4.1.3 on 2022-11-21 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_no', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=100)),
                ('stop_lat', models.FloatField()),
                ('stop_long', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='announcements',
            name='for_user',
            field=models.ForeignKey(default='bus', limit_choices_to=models.Q(('user_type', 'hos'), ('user_type', 'bus'), _connector='OR'), max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_no', models.IntegerField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=100)),
                ('stops', models.ManyToManyField(related_name='routes', to='tracker.stops')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_no', models.IntegerField(primary_key=True, serialize=False)),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='tracker.route')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('bus_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tracker.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tracker.route')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'hos'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
