# Generated by Django 4.1.3 on 2022-11-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_buscoordinates_stops_alter_announcements_for_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stops',
            name='stop_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
