# Generated by Django 4.1.3 on 2022-11-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_stops_stop_lat_alter_stops_stop_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_name',
        ),
    ]
