# Generated by Django 4.1.3 on 2022-11-22 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_announcements_for_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='user',
        ),
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'hos'}, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
