# Generated by Django 4.1.3 on 2022-11-22 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_rename_user_bookings_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='bus_no',
            new_name='bus',
        ),
        migrations.AddField(
            model_name='bookings',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateField(),
        ),
    ]
