# Generated by Django 4.1.3 on 2022-11-23 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_rename_bus_no_bookings_bus_bookings_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='bus_capacity',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
