# Generated by Django 4.1.3 on 2022-11-23 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_bookings_bus_capacity_alter_bus_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='users',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'hos'}, null=True, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
