# Generated by Django 4.1.3 on 2022-11-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_route_end_lat_route_end_long_route_start_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='end_lat',
        ),
        migrations.RemoveField(
            model_name='route',
            name='end_long',
        ),
    ]
