# Generated by Django 4.1.3 on 2022-11-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_rename_stop_long_stops_stop_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='start_long',
            new_name='start_lng',
        ),
    ]
