# Generated by Django 4.1.3 on 2022-11-26 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_remove_route_start_lat_remove_route_start_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='start_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_stop', to='tracker.stops'),
        ),
    ]
