# Generated by Django 4.1.3 on 2022-11-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_alter_route_start_stop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='stops',
            new_name='waypoints',
        ),
    ]
