# Generated by Django 4.1.3 on 2022-11-28 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_rename_stops_route_waypoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buscoordinates',
            name='bus_no',
        ),
        migrations.AddField(
            model_name='buscoordinates',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bus_coordinates', to='tracker.bus'),
        ),
    ]
