# Generated by Django 4.1.3 on 2022-11-28 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_remove_buscoordinates_bus_no_buscoordinates_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscoordinates',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_coordinates', to='tracker.bus'),
        ),
    ]
