# Generated by Django 4.1.3 on 2022-11-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_alter_buscoordinates_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscoordinates',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='buscoordinates',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
